stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
      - ls -la 
      - docker image build -t py-app-bot:v1-CI -f Dockerfile.bot .
      - docker image build -t py-app-proxy:v1-CI -f Dockerfile.nginx .
      - docker image build -t py-app-app:v1-CI -f Dockerfile.dev .
      - docker image build -t py-app-tests:v1-CI -f Dockerfile.tests .
      - docker image pull postgres:18
      - docker images

test-host-net:
  stage: test
  script:
    - apk add curl
    - curl localhost:8090

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
      - docker images
      - docker compose up -d
      - sleep 2
      - docker compose ps -a
      - sleep 15
      - docker compose logs tests 
      


#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  environment: production
#  script:
