FROM python:3.12-slim as builder

WORKDIR /app

COPY requirements.txt ./

RUN pip install --user -r requirements.txt


FROM python:3.12-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local

COPY /bot .

COPY .env .  

ENV PATH="/root/.local/bin:$PATH"

CMD ["python", "main.py"]
