FROM python:3.12-slim as builder

WORKDIR /app

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt ./
RUN pip install -r requirements.txt

FROM python:3.12-alpine

WORKDIR /app

RUN groupadd -r appuser && useradd -r -g appuser appuser

COPY --from=builder /opt/venv /opt/venv

COPY bot/ ./bot/

ENV PATH="/opt/venv/bin:$PATH"

CMD ["python", "main.py"]
