FROM python:3.12-slim

WORKDIR /app

COPY tests/requirements-dev.txt .
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install -r requirements-dev.txt

COPY . . 

ENV PYTHONPATH=/app

CMD ["python", "-m", "pytest", "tests/", "-v"]
