services:
  app:
    image: py-app-app:v1-CI
    container_name: py-app
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy  # ← Ждет healthcheck
  nginx:
    image: py-app-proxy:v1-CI
    container_name: py-app-proxy
    ports:
      - "8080:80"
    depends_on:
      - app
  postgres:
    container_name: py-app-db
    image: postgres:18
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=myapp
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d myapp"]
      interval: 2s
      timeout: 5s
      retries: 10
  bot:
    image: py-app-bot:v1-CI
   # command: python -m bot.main
    env_file: .env
    depends_on:
      - app
      - postgres

  tests:
    container_name: py-app-tests
    image: py-app-tests:v1-CI
    ports:
      - "5001:5001"
    command: >
      sh -c "cd /app/tests && 
             python -m pytest test_api.py -v"  # Только тесты API!
    depends_on:
      - app 
  #   prometheus:
  #   image: prom/prometheus
  #   container_name: py-app-metrics
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'
  #     - '--storage.tsdb.path=/prometheus'  
  #   restart: unless-stopped

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: py-app-grafana
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin 
  #   volumes:
  #     - grafana_data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
  #   restart: unless-stopped

volumes:
  postgres_data:
  grafana_data:
    
