FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

# RUN apt-get update && apt-get install sqlite3 && rm -rf /var/lib/apt/lists/*

COPY schema.sql app.py ./

EXPOSE 5000

CMD ["python", "app.py"]
